INSERT INTO rooms (room_id, user_id, name, location, bookable, notes) VALUES
                                                                          (1,  0, 'Laboratório 101', 'Primeiro Andar', 1, '30 Notebook Lenovo Thinkpad'),
                                                                          (2,  0, 'Laboratório 102', 'Primeiro Andar', 1, '37 computadores'),
                                                                          (3,  0, 'Laboratório 103', 'Primeiro Andar', 1, '21 computadores'),
                                                                          (4,  0, 'Laboratório 104', 'Primeiro Andar', 1, '24 computadores'),
                                                                          (5,  0, 'Laboratório 201', 'Segundo Andar',  1, '31 computadores'),
                                                                          (6,  0, 'Laboratório 202', 'Segundo Andar',  1, '37 computadores'),
                                                                          (7,  0, 'Laboratório 203', 'Segundo Andar',  1, '30 computadores'),
                                                                          (8,  0, 'Laboratório 204', 'Segundo Andar',  1, '30 computadores'),
                                                                          (9,  0, 'Auditório',       'Térreo',         1, NULL),
                                                                          (10, 0, 'Ensaios',         'Bloco C',        1, NULL),
                                                                          (11, 0, 'Lab Química',     'Bloco C',        1, NULL),
                                                                          (12, 0, 'Lab Metalografia','Bloco C',        1, NULL),
                                                                          (13, 0, 'Física',          'Bloco C',        1, NULL),
                                                                          (14, 0, 'Ferramentaria',   'Bloco C',        1, NULL),
                                                                          (15, 0, 'Lab Polímeros',   'Bloco C',        1, NULL),
                                                                          (16, 0, 'T02',             'Térreo',         1, '31 Notebook Lenovo Thinkpad'),
                                                                          (17, 0, 'T01',             'Térreo',         1, '40 Notebook Lenovo Thinkpad'),
                                                                          (18, 0, 'Lab 111',         'Primeiro Andar', 1, '42 Notebook Lenovo Thinkpad'),
                                                                          (19, 0, 'Lab 112',         'Primeiro Andar', 1, '29 Notebook Lenovo Thinkpad');